<a href="https://colab.research.google.com/github/Aldistwn29/Numpay_part1/blob/main/Numpy_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

numpy.ndarray(object dtype=None, copy=True, order=None, subok:False, ndmin=0)

*   object : objek apapun yg mengekspos antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
*   dtype : type data, opsional
copy: Opsional secara default(True), objek disalin
* order : C(baris mayor) atau F (Utama kolom) atau A(apa saja)(default)
* subok : Secara default, array yg di kembalikan di paksa menjadi array kelas dasar. Jika benar, sub-kelas akan di berikan
* ndimin : Menentukan dimensi minimum dari array yg dihasilkan  


In [ ]:
# contoh 1
# Masukkan nilai integer atau nilai dengan tipe data apapun sesui
# kebutuhan
arr =np.array([1, 2, 3])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
# mengindeks array
arr[1]

2

In [ ]:
# Contoh 2
# Array 2 dimensi
a = np.array([[1, 3],
             [2, 4]])

In [ ]:
print(a)

[[1 3]
 [2 4]]


# Tipe Data Array

In [ ]:
# contoh 1
# 1 array type data integer
print(a.dtype)

int64


In [ ]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan', 'jeruk', 'apel'])
print(arr_1.dtype)
arr_1 = np.array(['r', 'j', 'a'])
print(arr_1.dtype)

<U8
<U1


In [ ]:
# contoh 3
# tipe data yg di definisikan
arr_2 = np.array([1, 2, 3], dtype= 'S')
print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3']
|S1


membuat array dari yg sudah ada

In [8]:
# konsversi list menjadi ndarray

x = [1, 2, 3, 4, 5]
print(type(x))
print("===konversi list menjadi array===")
x = np.asarray(x)
print(x)
print(x.dtype)
print(type(x))

<class 'list'>
===konversi list menjadi array===
[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [19]:
# contoh kedua konversi list menjadi array dengan type data yg di definisikan

x = [1, 2, 3, 4, 5]
print(type(x))

print('konversi list menjadi array dengan type data float')
x = np.asarray(x, dtype='f')
print(x.dtype)
print(x)

<class 'list'>
konversi list menjadi array dengan type data float
float32
[1. 2. 3. 4. 5.]


Task untuk audience:


*   buat dua variabel tupel yg berisi angka
*   masukkan dua variabel tuple tersebut kedalam variabel bertipe list
* konverse list tersebut menjadi array numpy



In [28]:
# isi di sini
a = (1, 2, 3, 4, 5)
print(type(a))
b = (6, 7, 8, 9, 10)
print(type(b))
print('konversi tuple ke list')
c = list(a) + list(b)
print(type(c))
print(c)
print('konversi list ke array')
c = np.asarray(c)
print(c)
print(type(c))

<class 'tuple'>
<class 'tuple'>
konversi tuple ke list
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
konversi list ke array
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


membuat rentang nilai menggunakan numpy(Study Case): membuat dataframe menggunakan rentang nilai random dan deterministik numpy.arange(start, stop, step, dtype)

In [76]:
x = np.arange(0, 1, 0.1, dtype='f')
y = np.arange(1, 11, 1)
z = np.arange(10, 20, 1)

In [77]:
print(x)
print(y)
print(z)

[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]


In [70]:
# import library pandas
import pandas as pd

In [75]:
# a =({'x':x, 'y':y, 'z':z})
# df = pd.DataFrame.from_dict(a, orient='index')
# df.transpose()

x    y     z
0  0.0  1.0  10.0
1  0.1  2.0  11.0
2  0.2  3.0  12.0
3  0.3  4.0  13.0
4  0.4  5.0  14.0
5  0.5  6.0  15.0
6  0.6  7.0  16.0
7  0.7  8.0  17.0
8  0.8  9.0  18.0
9  0.9  NaN  19.0

In [78]:
pd.DataFrame({'x': x, 'y': y, 'z': z})

x   y   z
0  0.0   1  10
1  0.1   2  11
2  0.2   3  12
3  0.3   4  13
4  0.4   5  14
5  0.5   6  15
6  0.6   7  16
7  0.7   8  17
8  0.8   9  18
9  0.9  10  19

oprasi umum lain di Numpay beserta tugas

In [85]:
# membuat array dengan nilai 0 di numpy
# dengan baris 3 dan kolom 2
x = np.zeros((3,2))
print(x)
print("")
# dengan baris 2 dan kolom 3
x = np.zeros((2,3))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [86]:
# membuat array dengan nilai 1 di numpy
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [88]:
# mendefinisikan dengan nilai yg di inginkan
x = np.full((2,3), 2.1)
print(x)

[[2.1 2.1 2.1]
 [2.1 2.1 2.1]]


In [97]:
# membuat array dengan angka yg random
x = np.random.rand(6,3)
print(x)

[[0.04550232 0.94520504 0.71683549]
 [0.29594033 0.34684468 0.6885163 ]
 [0.16742866 0.58689331 0.1131946 ]
 [0.00951869 0.62798863 0.99163217]
 [0.1352789  0.98306305 0.11987165]
 [0.22255514 0.72593142 0.36468201]]


In [98]:
# menjadikan array dengan method random menjadi dataframe
pd.DataFrame(x, columns=['x', 'y', 'z'])

x         y         z
0  0.045502  0.945205  0.716835
1  0.295940  0.346845  0.688516
2  0.167429  0.586893  0.113195
3  0.009519  0.627989  0.991632
4  0.135279  0.983063  0.119872
5  0.222555  0.725931  0.364682

In [ ]:
# tugas 1: Generate random array menggunakan np.random.read dengan jumlah baris 3 serta jumlah kolom 4 dan masukkan ke dalam dataframe
# tugas 2: Generate random array menggunakan dengan nilai satu dan nol jumlah baris 5 serta jumlah kolom 6 di dua kolom berbeda kemudian konversi ke dataframe
#  dan concat keduanya

tugas 1

In [101]:
y = np.random.rand(3, 4)
print(y)

[[0.91332157 0.19979586 0.74601925 0.93194972]
 [0.27250742 0.67696859 0.69793311 0.38392636]
 [0.73043946 0.78783043 0.84417046 0.18618135]]


In [102]:
# memasukan data di atas(3, 4) kedalam dataframe
pd.DataFrame(y, columns=['x', 'y', 'z', 'a'])

x         y         z         a
0  0.913322  0.199796  0.746019  0.931950
1  0.272507  0.676969  0.697933  0.383926
2  0.730439  0.787830  0.844170  0.186181

tugas 2

In [103]:
# membuat matrik dengan nilai satu dan nol ukuran (5, 6)
x = np.ones((5, 6))
y = np.zeros((5, 6))
print(x)
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [114]:
e = pd.DataFrame(x, columns=['x', 'y', 'z', 'a', 'b', 'c'])

In [115]:
e

x    y    z    a    b    c
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0

In [112]:
f = pd.DataFrame(y, columns=['x', 'y', 'z', 'a', 'b', 'c'])

In [116]:
f

x    y    z    a    b    c
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0

In [125]:
# mengabungkan dengan concat
pd.concat([e, f])

x    y    z    a    b    c
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0

In [126]:
pd.concat([e, f], ignore_index=True)

x    y    z    a    b    c
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0
5  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0
8  0.0  0.0  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0  0.0  0.0

In [129]:
pd.concat([e, f], keys=['e', 'f'],
          names=['Nama variabel', 'Row Id'])

x    y    z    a    b    c
Nama variabel Row Id                              
e             0       1.0  1.0  1.0  1.0  1.0  1.0
              1       1.0  1.0  1.0  1.0  1.0  1.0
              2       1.0  1.0  1.0  1.0  1.0  1.0
              3       1.0  1.0  1.0  1.0  1.0  1.0
              4       1.0  1.0  1.0  1.0  1.0  1.0
f             0       0.0  0.0  0.0  0.0  0.0  0.0
              1       0.0  0.0  0.0  0.0  0.0  0.0
              2       0.0  0.0  0.0  0.0  0.0  0.0
              3       0.0  0.0  0.0  0.0  0.0  0.0
              4       0.0  0.0  0.0  0.0  0.0  0.0