<a href="https://colab.research.google.com/github/Aldistwn29/Numpay/blob/main/Numpy_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Array Itration

In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('Array yang telah di modifikasi:')
for x in np.nditer(a):
  print(x, end= ' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yang telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

In [ ]:
# Urutan iterasi dipilih agar sesui dengan tata letak mencari array,
# tanpa mempertimbangkan urutan tertentu
# contoh 2
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('Array yg di transponse:')
b = a.T
print(b)
print('\n')

print('Array yg telah di modifikasi:')
for x in np.nditer(b):
  print(x, end= ' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yg di transponse:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Array yg telah di modifikasi:
0 5 10 15 20 25 30 35 40 45 50 55 

# Itrasion orde

In [ ]:
# contoh 3
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('Array yg di transponse:')
b = a.T
print(b)
print('\n')

print('urutkan dalam C-style order:')
c = b.copy(order='C')
print(c)
for x in np.nditer(c):
  print(x, end=' ')

print('\n')

print('urutkan dalam F-style order:')
d = b.copy(order='F')
print(c)
for x in np.nditer(d):
  print(x, end=' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array yg di transponse:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


urutkan dalam C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

urutkan dalam F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [ ]:
# contoh 4
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('urutkan dalam C-style order:')
for x in np.nditer(a, order='C'):
  print(x, end=' ')

print('\n')

print('urutkan dalam C-style order:')
for x in np.nditer(a, order='F'):
  print(x, end=' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


urutkan dalam C-style order:
0 5 10 15 20 25 30 35 40 45 50 55 

urutkan dalam C-style order:
0 20 40 5 25 45 10 30 50 15 35 55 

# Modifikasi nilai elemen array

In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

for x in np.nditer(a, op_flags= ['readwrite']):
  x[...] = 2*x
print('Array Setelah di modifikasi:')
print(a)

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array Setelah di modifikasi:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


# Eksternal loop

In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('Array Setelah dimodifikasi:')
for x in np.nditer(a, flags= ['external_loop'], order='F'):
  print(x, end=' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array Setelah dimodifikasi:
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 

# Brodcasting itrasi array

In [ ]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Array Asli:')
print(a)
print('\n')

print('Array kedua:')
b = np.array([1,2,3,4], dtype=int)
print(b)
print('\n')

print('Array yg telah dimodifikasi:')
for x,y in np.nditer([a,b]):
  print("%d:%d" % (x,y), end=' ')

Array Asli:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Array kedua:
[1 2 3 4]


Array yg telah dimodifikasi:
0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

# Numpy for Mathematics

Fungsi Trigonometri
NumPy memiliki fungsi trigonometri standar yg mengembalikan rasio trigonometri untuk sudut tertentu dan radian.

In [ ]:
a = np.array([0,30,45,60,90])

print('Nilai sin dari yg berbeda-beda:')
# konversi radian dengan menampilkan dengan pi/180
print(np.sin(a*np.pi/180))
print('\n')

print('Nilai kosinus dari yg berbeda-beda:')
print(np.cos(a*np.pi/180))
print('\n')

print('Nilai tangent dari yg berbeda-beda:')
print(np.tan(a*np.pi/180))
print('\n')

Nilai sin dari yg berbeda-beda:
[0.         0.5        0.70710678 0.8660254  1.        ]


Nilai kosinus dari yg berbeda-beda:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Nilai tangent dari yg berbeda-beda:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]




In [ ]:
a = np.array([0,30,45,60,90])

print('Array dengan Niali Sinus:')
sin = np.sin(a*np.pi/180)
print(sin)
print('\n')


print('Hitung invers(kebalikan) sinus dari, Nilai yg dikembalikan dalam radian:')
inv = np.arcsin(sin)
print(sin)
print('\n')

print('Periksa hasil dengan mengkonversi ke drajat:')
print(np.degrees(inv))
print('\n')

print('Array dengan Niali cosinus:')
cos = np.cos(a*np.pi/180)
print(cos)
print('\n')


print('Hitung invers cosinus:')
inv = np.arccos(cos)
print(inv)
print('\n')

print('Periksa hasil dengan mengkonversi ke drajat:')
print(np.degrees(inv))
print('\n')

print('Array dengan Niali Tan:')
tan = np.tan(a*np.pi/180)
print(tan)
print('\n')


print('Hitung invers Tan dari:')
inv = np.arctan(tan)
print(inv)
print('\n')

print('Periksa hasil dengan mengkonversi ke drajat:')
print(np.degrees(inv))
print('\n')

Array dengan Niali Sinus:
[0.         0.5        0.70710678 0.8660254  1.        ]


Hitung invers(kebalikan) sinus dari, Nilai yg dikembalikan dalam radian:
[0.         0.5        0.70710678 0.8660254  1.        ]


Periksa hasil dengan mengkonversi ke drajat:
[ 0. 30. 45. 60. 90.]


Array dengan Niali cosinus:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Hitung invers cosinus:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Periksa hasil dengan mengkonversi ke drajat:
[ 0. 30. 45. 60. 90.]


Array dengan Niali Tan:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Hitung invers Tan dari:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Periksa hasil dengan mengkonversi ke drajat:
[ 0. 30. 45. 60. 90.]




# Fungsi Pembulatan dengan numpy.round

numpy.around(a, decimals)

In [ ]:
a = np.array([1.0,5.55,123,0.567,25.532])

print('Array asli')
print(a)
print('\n')

print('Array Setelah Pembulatan:')
print(np.around(a))
# membulatkan hanya 1 angka di belakang koma
print(np.around(a, decimals=1))

Array asli
[  1.      5.55  123.      0.567  25.532]


Array Setelah Pembulatan:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]


np.floor

Fungsi ini mengembalikan bilangan bulat terbesar yg tidak lebih besar dari prameter input. Dasar skalar x adalah bilangan bulat terbesar i, sehingga i <= x. Perhatikan bahwa dalam python, floor selalu dibulatkan dari 0.

In [ ]:
a = np.array([-1.7,1.5,-0.2,0.6,10.])

print('Array Asli:')
print(a)
print('\n')

print('Flooring array:')
print(np.floor(a))

Array Asli:
[-1.7  1.5 -0.2  0.6 10. ]


Flooring array:
[-2.  1. -1.  0. 10.]


# np.ceil

Fungsi ceil() mengembalikan plafon nilai input, yaitu ceil skalar x adalah bilangan bulat terkecil i, sehingga i >= x.

In [ ]:
a = np.array([-1.6,1.6,-1.3,0.7,10])

print('Array Asli:')
print(a)
print('\n')

print('ceilling array:')
print(np.ceil(a))

Array Asli:
[-1.6  1.6 -1.3  0.7 10. ]


ceilling array:
[-1.  2. -1.  1. 10.]


# Oprasi Aritmatika

di numpy ada fungsi untuk melakukan penjumlahan, pengurangan, perkalian dan pembagian.

In [ ]:
a = np.arange(9, dtype=np.float_).reshape(3,3)

print('Array Asli:')
print(a)
print('\n')

print('Array kedua:')
b = np.array([1,2,3])
print(b)
print('\n')

# melakukan brodcasting
print('Penjumlahan 2 Array:')
print(np.add(a,b))
print('\n')

print('Pengurangan 2 Array:')
print(np.subtract(a,b))
print('\n')

print('Perkalian 2 Array:')
print(np.multiply(a,b))
print('\n')

print('Pembagian 2 Array:')
print(np.divide(a,b))

Array Asli:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Array kedua:
[1 2 3]


Penjumlahan 2 Array:
[[ 1.  3.  5.]
 [ 4.  6.  8.]
 [ 7.  9. 11.]]


Pengurangan 2 Array:
[[-1. -1. -1.]
 [ 2.  2.  2.]
 [ 5.  5.  5.]]


Perkalian 2 Array:
[[ 0.  2.  6.]
 [ 3.  8. 15.]
 [ 6. 14. 24.]]


Pembagian 2 Array:
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]


Operasi Pangkat dua dengan np.power

In [ ]:
a = np.array([10,100,1000])

print('Array Asli:')
print(a)

print('Menggunakan power function:')
print(np.power(a,3))
print('\n')

print('Array kedua:')
b = np.array([1,2,3])
print(b)

print('Menggunakan power function:')
print(np.power(a,b))

Array Asli:
[  10  100 1000]
Menggunakan power function:
[      1000    1000000 1000000000]


Array kedua:
[1 2 3]
Menggunakan power function:
[        10      10000 1000000000]


Mengambil nilai sisa dengan np.mod() atau np.remainder()

In [ ]:
a = np.array([20,30,40,50])
b = np.array([2,4,5,6])

print('Array pertama:')
print(a)
print('\n')

print('Array Kedua:')
print(b)
print('\n')

print('Menggunakan mod():')
print(np.mod(a,b))
print('\n')

print('menggunakan remainder():')
print(np.remainder(a,b))
print('\n')

Array pertama:
[20 30 40 50]


Array Kedua:
[2 4 5 6]


Menggunakan mod():
[0 2 0 2]


menggunakan remainder():
[0 2 0 2]




# Fungsi Statistika

In [ ]:
# mencari nilai minimum dan maximum dalam Suatu array

a = np.array([[3,7,5],[8,4,3],[2,3,9]])

print('Array Asli:')
print(a)
print('\n')

print('Menggunakan amin() function:')
print(np.amin(a))
print('\n')

print('menggunakan amin() fungsion berdasarkan baris:')
print(np.amin(a, axis=0))
print('\n')

print('menggunakan amin() fungsion berdasarkan colom:')
print(np.amin(a, axis=1))
print('\n')

print('menggunakan amax() fungsion:')
print(np.amax(a))
print('\n')

print('menggunakan amax() fungsion berdasarkan colum:')
print(np.amax(a, axis=0))
print('\n')

Array Asli:
[[3 7 5]
 [8 4 3]
 [2 3 9]]


Menggunakan amin() function:
2


menggunakan amin() fungsion berdasarkan baris:
[2 3 3]


menggunakan amin() fungsion berdasarkan colom:
[3 3 2]


menggunakan amax() fungsion:
9


menggunakan amax() fungsion berdasarkan colum:
[8 7 9]




np.percentile

Persentil (atau satu persentil) adalah ukuran yang digunakan dalam statistik yang menunjukkan nilai di bawah persentase pengamatan tertentu dalam kelompok pengamatan.

numpy.percentile(a, q, axis)

a : Input array

q : Persentil yang akan dihitung harus antara 0-100

axis : sumbu

Persentil untuk nilai dalam kumpulan data tertentu dapat dihitung menggunakan rumus:

n = (P/100) x N

di mana N = jumlah nilai dalam kumpulan data, P = persentil, dan n = peringkat ordinal dari nilai yang diberikan (dengan nilai dalam kumpulan data diurutkan dari terkecil ke terbesar). Misalnya, ambil kelas yang terdiri dari 20 siswa yang memperoleh nilai berikut pada tes terbaru mereka: 75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90. Skor ini dapat direpresentasikan sebagai kumpulan data dengan 20 nilai: {75, 77, 78, 78, 80, 81, 81, 82, 83, 84, 84, 84, 85, 87, 87, 88, 88, 88, 89, 90}.

Kita dapat menemukan skor yang menandai persentil ke-20 dengan memasukkan nilai yang diketahui ke dalam rumus dan menyelesaikan n:

n = (20/100) x 20

n = 4

Nilai keempat dalam kumpulan data adalah skor 78. Ini berarti bahwa 78 menandai persentil ke-20; dari siswa di kelas, 20 persen memperoleh skor 78 atau lebih rendah.



In [13]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print('Array Asli:')
print(a)
print('\n')

print('menggunakan percentile() function:')
print(np.percentile(a, 50))
print('\n')

print('Mengurutkan Array:')
print(np.sort(a, axis=None))
print('\n')

print('menggunakan percentile function di sumbu 1:')
print(np.sort(a, axis=1))
print('\n')
print(np.percentile(a,50, axis=1))
print('\n')

print('menggunakan percentile function di sumbu 0:')
print(np.sort(a, axis=0))
print('\n')
print(np.percentile(a,50, axis=0))
print('\n')

Array Asli:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


menggunakan percentile() function:
50.0


Mengurutkan Array:
[10 20 30 40 50 60 70 80 90]


menggunakan percentile function di sumbu 1:
[[30 40 70]
 [10 20 80]
 [50 60 90]]


[40. 20. 60.]


menggunakan percentile function di sumbu 0:
[[30 20 10]
 [50 40 60]
 [80 90 70]]


[50. 40. 60.]




Median didefinisikan sebagai nilai yg memisahkan bagian dari yg lebih tinggi data dari bagian yg lebih rendah, dan bisa di hitung menggunakan numpy.median

In [20]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])

print('Array Asli:')
print(a)
print('\n')

print('Menggunakan Median Function():')
print(np.median(a))
print('\n')

print('Menggunakan Median Function() dengan perspektif Colum:')
print(np.median(a, axis=1))
print('\n')

print('Menggunakan Median Function() dengan perspektif Baris:')
print(np.median(a, axis=0))
print('\n')

Array Asli:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Menggunakan Median Function():
65.0


Menggunakan Median Function() dengan perspektif Colum:
[65. 80. 60.]


Menggunakan Median Function() dengan perspektif Baris:
[50. 90. 60.]




Rata-Rata(Mean) adalah jumlah elemen sepanjang sumbu dibagi dengan jumlah elemen. Fungsi Numpy.mean() mengembalikan mean aritmatika elemen dalam array. Jika sumbu disebutkan secara eksplisit, maka akan dihitung berdasarkan nilai sumbunya.

In [25]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print('Array Asli:')
print(a)
print('\n')

print('Menggunakan Mean() function:')
print(np.mean(a))
print('\n')

print('Menggunakan mean() function berdasarkan perspektif colum:')
print(np.mean(a, axis=1))
print('\n')

print('Menggunakan mean() function berdasarkan perspektif baris:')
print(np.mean(a, axis=0))
print('\n')

Array Asli:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Menggunakan Mean() function:
3.6666666666666665


Menggunakan mean() function berdasarkan perspektif colum:
[2. 4. 5.]


Menggunakan mean() function berdasarkan perspektif baris:
[2.66666667 3.66666667 4.66666667]




Rata-rata tertimbang adalah rata-rata yang dihasilkan dari perkalian setiap komponen dengan faktor yang mencerminkan kepentingannya. Fungsi numpy.average() menghitung rata-rata tertimbang elemen dalam array sesuai dengan bobot masing-masing yang diberikan dalam array lain. Fungsi dapat memiliki parameter sumbu. Jika sumbu tidak ditentukan, array diratakan.

Mempertimbangkan array [1,2,3,4] dan bobot yang sesuai [4,3,2,1], rata-rata tertimbang dihitung dengan menambahkan produk dari elemen yang sesuai dan membagi jumlah dengan jumlah bobot.

Rata-rata tertimbang = (14+23+32+41)/(4+3+2+1)

In [30]:
a = np.array([1,2,3,4])

print('Array Asli:')
print(a)
print('\n')

print('Menggunakan average() function:')
print(np.average(a))
print('\n')

# this is same as mean when is not specified
wts = np.array([4,3,2,1])

print('Menggunakan average() function:')
print(np.average(a, weights=wts))
print('\n')

# Return the sum of weights, if the returend parameter is set to true
print('Sum of wights:')
print(np.average(a, weights= [4,3,2,1], returned=True))

Array Asli:
[1 2 3 4]


Menggunakan average() function:
2.5


Menggunakan average() function:
2.0


Sum of wights:
(2.0, 10.0)


Standar deviasi adalah ukuran seberapa tersebar data dalam kaitannya dengan mean. Standar deviasi rendah berarti data mengelompokan di sekitar rata-rata, dan standar deviasi tinggi menunjukkan data lebih tersebar

In [32]:
np.std([1,3,5,7])

2.23606797749979

Varians adalah ukuran variabilitas. ini di hitung dengan mengambil rata-rata deviasi kuadrat dari mean. Varians memberitahu anda tingkat penyebaran dalam kumpulan data anda. semakin menyebar data, semakin besar varians dalam kaitannya dengan mean.

In [33]:
print(np.var([1,3,5,7]))

5.0


In [34]:
np.sqrt(np.var([1,3,5,7]))

2.23606797749979

Standar deviasi mengukur seberapa jauh angka-angka dalam kumpulan data. Varians, di sisi lain, memberikan nilai aktual seberapa banyak angka dalam kumpulan data bervariasi dari rata-rata.